// src/routes/admin.routes.js
/*
  Placeholder file generated by bootstrap.sh
  Fill this file with your implementation.
*/

const express = require('express');
const router = express.Router();
const { authenticate } = require('../middlewares/auth.middleware');
const { authorizeRoles } = require('../middlewares/role.middleware');

router.use(authenticate);
router.use(authorizeRoles('admin'));

/**
 * @openapi
 * /api/admin/users:
 *   get:
 *     tags: [Admin]
 *     summary: List users (admin only)
 *     responses:
 *       200:
 *         description: User list
 *       403:
 *         description: Forbidden
 */
router.get('/users', (req, res) => res.json([]));

module.exports = router;
