// src/routes/report.routes.js
/*
  Placeholder file generated by bootstrap.sh
  Fill this file with your implementation.
*/

const express = require('express');
const router = express.Router();
const { authenticate } = require('../middlewares/auth.middleware');

router.use(authenticate);

/**
 * @openapi
 * /api/reports:
 *   get:
 *     tags: [Reports]
 *     summary: List reports
 *     responses:
 *       200:
 *         description: Report list
 *         content:
 *           application/json:
 *             schema:
 *               type: array
 *               items: { $ref: '#/components/schemas/Report' }
 */
router.get('/', (req, res) => res.json([]));

module.exports = router;
